### ISSUE TITLE
memory leak

### ISSUE THREAD

**Issue by robertovaldesperez** [latelierco/vue-signalr#42]
MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 init listeners added. Use emitter.setMaxListeners() to increase limit
    at _addListener (webpack-internal:///./node_modules/events/events.js:211:15)
    at SocketConnection.addListener (webpack-internal:///./node_modules/events/events.js:227:10)
    at SocketConnection.listen (webpack-internal:///./node_modules/@latelier/vue-signalr/dist/vue-signalr.js:236:12)
    at eval (webpack-internal:///./node_modules/@latelier/vue-signalr/dist/vue-signalr.js:377:18)
    at Array.forEach (<anonymous>)
    at VueComponent.created (webpack-internal:///./node_modules/@latelier/vue-signalr/dist/vue-signalr.js:376:17)
    at invokeWithErrorHandling (webpack-internal:///./node_modules/vue/dist/vue.esm.js:1871:57)
    at callHook (webpack-internal:///./node_modules/vue/dist/vue.esm.js:4238:7)
    at Vue._init (webpack-internal:///./node_modules/vue/dist/vue.esm.js:5021:5)
    at new VueComponent (webpack-internal:///./node_modules/vue/dist/vue.esm.js:5167:12)

**Comment by robertovaldesperez** [comment]
@Stoolbend @Alxios @Mikatux @atomikdesign can you help me?
